language: node_js
node_js:
- '5.2.0'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: fJW0k+LXNURR/hpwkPJQIgOzjYeUFkK3/lGyERohRclgDK93k3bYGb1T9lUfbjwB6jOnYHxbCTKqHTn7PUx4l1xZGPgNQ/0fLHpqSG5HChJ3iGxcbU5TluZ1VGRx88QVO4CTQtia4pptbdC/4onNZvT1Cn4rdl2VO1OYxjYYt6VRlf4o+1xgbL7wXI83aA4K93Asa1aVCVROFj+4ZGMC5ciRWURZgDKR5gOUu1xGkFYxM+I7dvcoFQO6OS8HrK7OscfW9Wi1tux3khalLqxB6WiDo8SUYUezcPwJAaOvmp1IkEKaonVRhPfLSSXJGBeuparAsmqrabh4gHyF7ONJs9quGBoX0LdEdhKTHCy7g18oD7/dhLzAPlJPEBOhC3XU1V+EG9LHWnlZvN70GIqrWNr7kgWpbqi9ehemR8n4r4gTAF09Mj6uQ7TcBqTARxGeSdqAer+vwDu1OoTCLMsvAvA8UDtpsDXjg2FjSq96s6DDZnEuAWd15CIf+3LSDOlOHnS9gJN+gL+T/Dx7M6ZNRTLqEL0oxDi66AKMxl/4V2+ojPNCZXoKLvpvcqnTm4u4oXwcg+FFJYYAoCgjP6q6phciE8BZVZAG/y2C8JQqndXcYManUBLwAj9Huc4Zck8jli/vApowzpAWPLAwnZcy3ZPmrOHrBBjeNsHztB3fDvQ=
  app: blooming-crag-5072